import { SimpleSQLLexer } from '../dist/index';
import { Token } from 'antlr4ts';

test('SimpleSQLLexer correctly parses SQL queries', () => {
  let sqlString = 'SELECT * FROM table';
  let lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = '  SELECT \t* \r\n FROM  table   ';
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = "SELECT * FROM table WHERE column = 'test'";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().text).toBe('WHERE');
  expect(lexer.nextToken().text).toBe('column');
  expect(lexer.nextToken().text).toBe('=');
  expect(lexer.nextToken().text).toBe("'test'");
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = "SELECT * FROM table WHERE column = 'test and a missing quote";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().text).toBe('WHERE');
  expect(lexer.nextToken().text).toBe('column');
  expect(lexer.nextToken().text).toBe('=');
  expect(lexer.nextToken().text).toBe("'test and a missing quote");
  expect(lexer.nextToken().type !== Token.EOF);

  sqlString = "SELECT * FROM table WHERE column = 'test and a \r\n newline'   ";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().text).toBe('WHERE');
  expect(lexer.nextToken().text).toBe('column');
  expect(lexer.nextToken().text).toBe('=');
  expect(lexer.nextToken().text).toBe("'test and a \r\n newline'");
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = "SELECT * FROM table; SELECT * FROM table2 ;SELECT * FROM table3;SELECT * FROM table4 ; ";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table2');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table3');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table4');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = "SELECT * FROM table1 t1 where t1.column1 = 0;";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table1');
  expect(lexer.nextToken().text).toBe('t1');
  expect(lexer.nextToken().text).toBe('where');
  expect(lexer.nextToken().text).toBe('t1');
  expect(lexer.nextToken().text).toBe('.');
  expect(lexer.nextToken().text).toBe('column1');
  expect(lexer.nextToken().text).toBe('=');
  expect(lexer.nextToken().text).toBe('0');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().type).toBe(Token.EOF);

  sqlString = "SELECT * FROM table1 t1 where (t1.column1 = 0);";
  lexer = new SimpleSQLLexer(sqlString);
  expect(lexer.nextToken().text).toBe('SELECT');
  expect(lexer.nextToken().text).toBe('*');
  expect(lexer.nextToken().text).toBe('FROM');
  expect(lexer.nextToken().text).toBe('table1');
  expect(lexer.nextToken().text).toBe('t1');
  expect(lexer.nextToken().text).toBe('where');
  expect(lexer.nextToken().text).toBe('(');
  expect(lexer.nextToken().text).toBe('t1');
  expect(lexer.nextToken().text).toBe('.');
  expect(lexer.nextToken().text).toBe('column1');
  expect(lexer.nextToken().text).toBe('=');
  expect(lexer.nextToken().text).toBe('0');
  expect(lexer.nextToken().text).toBe(')');
  expect(lexer.nextToken().text).toBe(';');
  expect(lexer.nextToken().type).toBe(Token.EOF);

});