export enum ParsingErrorType {
  FAILED_PREDICATE = 'FAILED_PREDICATE',
  MISSING_TOKEN = 'MISSING_TOKEN',
  MISMATCHED_INPUT = 'MISMATCHED_INPUT',
  NO_VIABLE_ALTERNATIVE = 'NO_VIABLE_ALTERNATIVE',
  UNWANTED_TOKEN = 'UNWANTED_TOKEN'
}